name: Build and Test

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'

      - name: Install dependencies
        run: |
          python -m venv .venv
          source .venv/bin/activate
          pip install -r requirements.txt
          pip install flake8

      - name: Format code
        run: |
          mmake format

      - name: Run Linting
        run: |
          source .venv/bin/activate
          flake8 --ignore=E501,W504,W503 src/ tests/

      - name: Run Tests
        run: |
          source .venv/bin/activate
          python -m unittest discover -s tests

