name: Build and Test

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3
        with:
          lfs: true  # if you have large files like model or data managed via Git LFS

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'

      - name: Set up virtual environment and install dependencies
        run: |
          python -m venv .venv
          . .venv/bin/activate
          pip install --upgrade pip
          pip install -r requirements.txt
          pip install flake8 black gdown

      - name: Verify venv created
        run: |
          ls -l .venv

      - name: Download Model File from Google Drive
        run: |
          . .venv/bin/activate
          FILE_ID="17r2m4Udb7X2ZR31BFB1aClkD_PKFNsfR"
          FILE_NAME="gender_recognition_DOE_run6.h5"
          gdown $FILE_ID -O $FILE_NAME
          ls -lh $FILE_NAME  # Confirm file exists

      - name: Verify Data Folder Exists
        run: |
          echo "Listing data/ directory..."
          ls -l data

      - name: Format code
        run: |
          . .venv/bin/activate
          make format

      - name: Run Linting
        run: |
          . .venv/bin/activate
          flake8 --ignore=E501,W504,W503,E203 src/ tests/

      - name: Run tests
        run: |
          make test || true
