name: Build and Test

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'

      - name: Install dependencies
        run: |
          python -m venv .venv
          . .venv/bin/activate
          pip install -r requirements.txt
          pip install flake8 black gdown

      - name: Debug GitHub Actions Environment
        run: |
          echo "Current Working Directory:"
          pwd
          echo "Files in Workspace:"
          ls -l

      - name: Download Model File from Google Drive
        run: |
          . .venv/bin/activate
          FILE_ID="17r2m4Udb7X2ZR31BFB1aClkD_PKFNsfR"
          FILE_NAME="gender_recognition_DOE_run6.h5"
          gdown $FILE_ID -O $FILE_NAME
          ls -lh $FILE_NAME  # Confirm it exists

      - name: Verify Model File Exists
        run: |
          if [ ! -f "gender_recognition_DOE_run6.h5" ]; then
            echo "Error: Model file not found!"
            exit 1
          fi
          echo "Model file downloaded successfully!"

      - name: Checkout repo
        uses: actions/checkout@v3
        with:
          lfs: true
      
      - name: Git LFS Pull (if needed)
        run: |
          git lfs pull

      - name: Format code
        run: |
          . .venv/bin/activate
          make format

      - name: Run Linting
        run: |
          . .venv/bin/activate
          flake8 --ignore=E501,W504,W503,E203 src/ tests/

      - name: Run Tests
        run: |
          . .venv/bin/activate
          python -m unittest discover -s tests
